### ISSUE TITLE
Create Swift 2.3 and Swift 3.0 branches to keep up to date as betas progress

### ISSUE THREAD

**Issue by mattbischoff** [Lickability/PinpointKit#123]

**Comment by mliberatore** [comment]
These branches now exist and are being kept up-to-date:

- `swift-2.3`
- `swift-3.0`

**Comment by mattbischoff** [comment]
How should we signal these in the README?

**Comment by mliberatore** [comment]
Hmm, maybe an addendum to the "Installation" section? It’s the only section in which we currently refer to a specific version of `PinpointKit`. Though we do have a requirements section which lists:

> - iOS 9.0+
> - Xcode 7.3+

We could expand on this section, mention the branch names and the updated Xcode requirement for those branches?

**Comment by mattbischoff** [comment]
> We could expand on this section, mention the branch names and the updated Xcode requirement for those branches?

Ooh, that’s cool. We should also probably take a look at other projects to see what folks are doing if they’ve handled this yet.

**Comment by mliberatore** [comment]
Yup! Taking a look now, trying to find some.
