### ISSUE TITLE
Can't set feedback recipients on default PinpointKit

### ISSUE THREAD

**Issue by exsortis** [Lickability/PinpointKit#124]
The feedback recipients is left blank on the default PinpointKit instance, and it requires a convoluted series of object initialization just to set a property that should *always* be set by the app. 

It should be possible to do this:

```
    lazy var window: UIWindow? = ShakeDetectingWindow(frame: UIScreen.mainScreen().bounds, delegate: PinpointKit.defaultPinpointKit)

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.

        PinpointKit.defaultPinpointKit.configuration.feedbackRecipients = ["bugs@mysoftware.com"]
    }
```

**Comment by factotvm** [comment]
Having the current way of using the ShakeDetectingWindow and setting the feedbackRecipients documented would be very helpful until a time when the proposed solution is implemented. It seems like a common use case.

**Comment by mattbischoff** [comment]
@exsortis @factotvm If you point your dependency manager of choice to the latest commit on the develop branch, you should be able to much more easily specify the feedback recipients. Thanks again for the feedback!
