### ISSUE TITLE
(iOS 10) Visual Stutter When Hiding Status Bar

### ISSUE THREAD

**Issue by mliberatore** [Lickability/PinpointKit#126]
There’s an animation issue with status bar hiding when running the example project on iOS 10.

- [ ] Determine if this is an iOS 10 SDK bug and file a radar or address the issue.

#### To reproduce:
- Checkout the `swift-2.3` branch
- Run the example app in Xcode 8
- Tap the screenshot to bring up the editor
- Observe the stutter near the status bar and the navigation bar contents slightly overlapping the bar’s bottom border during the transition

![visual-stutter](https://cloud.githubusercontent.com/assets/7883805/16340946/9f32b810-39f8-11e6-8ad8-89d1272375a6.gif)

**Comment by mattbischoff** [comment]
Retest in beta 2

**Comment by mliberatore** [comment]
Fixed in beta 2! 🎈
![beta-2](https://cloud.githubusercontent.com/assets/7883805/16699318/774f528e-4521-11e6-82cc-7e05fe2e43f5.gif)

**Comment by mattbischoff** [comment]
Love when Apple fixes their bugs!
