### ISSUE TITLE
(iOS 10) Large Gap on Feedback View

### ISSUE THREAD

**Issue by mliberatore** [Lickability/PinpointKit#128]
On iOS 10, there’s a lot of space between components:
![simulator screen shot jun 24 2016 3 18 02 pm](https://cloud.githubusercontent.com/assets/7883805/16348175/fec77f74-3a1e-11e6-8943-ffc75271f1eb.png)

**Comment by mattbischoff** [comment]
Retest in beta 2

**Comment by mliberatore** [comment]
Still occurs in beta 2. Warrants more investigation at this point.

**Comment by mliberatore** [comment]
Still occurs in beta 3.

**Comment by mliberatore** [comment]
Merged on `swift-3.0`, but still awaiting the fix to be made in `swift-2.3`.

**Comment by mliberatore** [comment]
Closing. This was completed in #180.
