### ISSUE TITLE
ApplicationInformation is Unused

### ISSUE THREAD

**Issue by mliberatore** [Lickability/PinpointKit#139]
`Feedback` has an `ApplicationInformation` struct (and `applicationInformation` property) which could be useful. We’re not currently setting this property, but rather just defaulting it to `nil` when we instantiate a `Feedback` within `FeedbackViewController`.
- At the very least, we should populate this information such that a custom `Sender` could make use of it if they wanted to.
- We should also consider the _optional_ ability to automatically attach this information or perhaps prepend log data when using `MailSender`.

**Comment by ghubaddole** [comment]
This will be very nice indeed. I'd like to put a few lines of debugging information in the email sent. How do I do this at the moment?

**Comment by mliberatore** [comment]
@ghubaddole you could initialize your `PinpointKit` instance using custom `FeedbackConfiguration` which allows you to specify any email body you’d like. Additionally, if you don’t want your debug information in the email body, you could add it to the `additionalInformation` dictionary which gets converted to a JSON file that is attached to the message. As an example, I replaced [this line in the example app](https://github.com/Lickability/PinpointKit/blob/e4e45703259bb556f5c9da79409972ebe7de0f8e/Example/PinpointKitExample/ViewController.swift#L14) with the following:

```swift
let pinpointKit: PinpointKit = {
    
    // Configure the body of all messages.
    let body = FeedbackConfiguration.Body("This is the body of the email. You could put some debug information here if you’d like.")
    
    // Configure the additional information attached as JSON to all messages.
    let additionalInformation: [String: AnyObject] = [
        "key1": "value1" as NSString,
        "key2": "value2" as NSString,
        "key3": "value3" as NSString
    ]
    
    // Create the feedback configuration with both of these pieces of information.
    let feedbackConfiguration = FeedbackConfiguration(recipients: ["feedback@example.com"], body: body, additionalInformation: additionalInformation)
    
    // Create a Configuration object, and only customize the feedbackConfiguration with the version we created.
    let configuration = Configuration(feedbackConfiguration: feedbackConfiguration)
    
    // Initialize PinpointKit with this configuration.
    return PinpointKit(configuration: configuration)
}()
```

The example above would attach a file called `info.json` to the message with the following information:

```json
{
  "key1" : "value1",
  "key3" : "value3",
  "key2" : "value2"
}
```

You could simply replace the keys and values in that dictionary with any information you’d like to include for debugging purposes.
