### ISSUE TITLE
Usage code does not work with current version (0.9) when installed with cocoapods

### ISSUE THREAD

**Issue by fvvliet** [Lickability/PinpointKit#147]
Hello Pinpoint users,

When I install PinpointKit with Cocoapods and follow the 'Usage' section the example code does not work -> parameter 'feedbackRecipients' does not exist.

> private let pinpointKit = PinpointKit(feedbackRecipients: ["feedback@example.com"])
> lazy var window: UIWindow? = ShakeDetectingWindow(frame: UIScreen.mainScreen().bounds, delegate: self.pinpointKit)
> 

Can it be updated please ?
Thanks
Frank

**Comment by mliberatore** [comment]
Hey, @fvvliet! The code that allows for the specification of feedback recipients wasn’t available in the `0.9` release. It was added to address https://github.com/Lickability/PinpointKit/issues/124. You can see the usage section in the README for the `0.9` release here: https://github.com/Lickability/PinpointKit/tree/0.9.

If you’d like to use the `PinpointKit` initializer that allows for specification of feedback recipients before the next release is made, please instead use the following in your Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'YOUR_TARGET_NAME_HERE' do
	pod 'PinpointKit', :git => 'https://github.com/Lickability/PinpointKit.git', :branch => 'develop'
end
```

Don’t forget to replace `YOUR_TARGET_NAME_HERE` with your app’s actual target name. Then, you should be able to use the mechanism that you mentioned above in your `AppDelegate`:

```swift
private let pinpointKit = PinpointKit(feedbackRecipients: ["feedback@example.com"])
lazy var window: UIWindow? = ShakeDetectingWindow(frame: UIScreen.mainScreen().bounds, delegate: self.pinpointKit)
```

Let us know if that solves your issue, and thanks for trying out PinpointKit!
