### ISSUE TITLE
Cannot use feedback in sendFeedback

### ISSUE THREAD

**Issue by zellau** [Lickability/PinpointKit#158]
I'm trying to override MailSender's sendFeedback method. When I try to access feedback.screenshot, I get an error saying that "Value of type 'Feedback' has no member 'screenshot'" When I click through to see what Feedback looks like, I see an empty struct. I can't figure out how to point it at the useful struct defined in Feedback.swift and get the data from it.

**Comment by bcapps** [comment]
Hey, @zellau! The code that publicizes properties on the `Feedback` struct wasn’t available in the `0.9` release.

If you’d like to access the properties of `Feedback` in your subclass, please instead use the following code in your Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'YOUR_TARGET_NAME_HERE' do
	pod 'PinpointKit', :git => 'https://github.com/Lickability/PinpointKit.git', :branch => 'develop'
end
```

Don’t forget to replace `YOUR_TARGET_NAME_HERE` with your app’s actual target name. Then, you should be able to access the `screenshot` property of `Feedback` without incident.

Let us know if that solves your issue, and thanks for trying out PinpointKit!

**Comment by zellau** [comment]
I'm using Carthage. What's the equivalent to use for that?

**Comment by mattbischoff** [comment]
@zellau In Carthage, it’d be changing the line in your Cartfile to `github "lickability/PinpointKit" "develop"` and then running `carthage update`. Let us know if that works.

**Comment by mliberatore** [comment]
Closing this issue given the Carthage instructions provided above. @zellau, please re-open if you still need assistance with this, and thanks for checking out PinpointKit!
