### ISSUE TITLE
iOS 8.0 compatibility 

### ISSUE THREAD

**Issue by anas10** [Lickability/PinpointKit#164]
Hello,

The library is tagged as iOS 9.0+, that means it's not possible to install it via cocoapods on a project with platform iOS 8.0. 
Does the library use some calls that are not available before iOS 9.0 or is it just that it hasn't been tested prior to it ?

**Comment by mattbischoff** [comment]
@anas10 PinpointKit relies on APIs introduced in iOS 9, including `UIStackView`. We have no plans to backport the library to iOS 8, but we’d be happy to consider pull requests to that effect.
