### ISSUE TITLE
Cocoapods version does not support Swift3

### ISSUE THREAD

**Issue by salmankhann** [Lickability/PinpointKit#167]
Getting the 0.9 version from Cocoapods does not work in the Swift Project. However the develop branch works if added as a git submodule. That has a bug where the send and cancel button does not work in the MFMailComposer which has been fixed by #166

**Comment by mliberatore** [comment]
@salamankhann, we’re currently in progress getting our 1.0, Swift 3 release in order. For the time being, you could use what’s on `develop` via CocoaPods with:

```
pod 'PinpointKit', :git => 'https://github.com/Lickability/PinpointKit.git', :branch => 'develop'
```
