### ISSUE TITLE
Tapping "Send" does nothing. feedbackDelegate always nil.

### ISSUE THREAD

**Issue by freak4pc** [Lickability/PinpointKit#186]
Hey There.

Have been messing around with the library (on the swift-2.3 branch) and it seems tapping *Send* doesn't actually do anything. When logging around it seems the issue is here

```swift
feedbackDelegate?.feedbackCollector(self, didCollectFeedback: feedbackToSend)
``` 

for some reason feedbackDelegate is always `nil`. 
I have tried setting the delegate manually but that still returns `nil` for some reason. 

```swift
let collector   = FeedbackNavigationController()
collector.feedbackDelegate = self

let fbconf  = FeedbackConfiguration(recipients: ["my@email.com"])
let conf = Configuration(sender: sender, feedbackCollector: collector, feedbackConfiguration: fbconf)
````

Any thoughts on what could cause this?

**Comment by mliberatore** [comment]
Hi @freak4pc, thanks for trying out PinpointKit! Can you take a look at the solution I commented [here](https://github.com/Lickability/PinpointKit/issues/150#issuecomment-237881750)? It sounds like it might be the same issue. Quoted below:

> I believe your issue is that nothing is holding a strong reference to the `PinpointKit` instance you’re creating, and therefore the `feedbackDelegate` is `nil`’d out (note: `feedbackDelegate`, which is `weak`, is set to `self` in `PinpointKit`’s initializer.) To confirm this, set a breakpoint in `sendButtonTapped()`, and confirm that  `feedbackDelegate` is actually `nil` at this point when you tap "Send". If that’s the case, this is why the "Send" action isn’t reported back to you via delegation.

> The reason  using `defaultPinpointKit` works is because it’s a `static let`, and therefore a strong reference is held to it throughout the duration of the app’s life. To fix your issue, you should declare your `pinpointKit` constant somewhere else, such that a strong reference is kept. For example, if the `class` or `struct` you’re calling `pinpointKit.show(fromViewController: viewController)` from is around for the duration of PinpointKit’s use, declare it as a `class` or `struct`-level constant, instead of a property declared within the method from which you’re calling `show(fromViewController:)`.

Please let me know if this makes sense, and if it works for you.

**Comment by freak4pc** [comment]
Thanks @mliberatore , That does solve it. 
I was thinking about the same issue , but was sure the problem was the delegate wasn't a strong reference, so I've tired that. Thanks for _pinpointing_ the problem ;-) 

By the way, is there any best practice towards gathering feedback text from the user as well, except for adding custom UI to handle that post-screenshot?

**Comment by mliberatore** [comment]
> Thanks for pinpointing the problem ;-)

Ha! 😄 No problem!

> is there any best practice towards gathering feedback text from the user as well, except for adding custom UI to handle that post-screenshot?

The user is able to add text in the mail compose view that appears when tapping Send, but beyond that, we don’t currently expose a means for adding additional text.
