### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by dasmer** [Lickability/PinpointKit#187]
It looks like the Swift 3 branch was deleted? It used to exist and is still live at commit 32c63256cc6f32bccc0bfb4a331070354ad76b2a

Any chance a maintainer can add that branch back?

**Comment by mliberatore** [comment]
Hi, @dasmer! The `swift-3.0` branch has been merged into `develop`, which has the most up-to-date work in preparation for our next release. Please checkout `develop`, and let me know if that solves your issue. Thanks, and apologies for any confusion!

**Comment by dasmer** [comment]
This works! THanks!!
