### ISSUE TITLE
[Manual installation] Logging?

### ISSUE THREAD

**Issue by iosdeveloper** [Lickability/PinpointKit#212]
Neither `NSLog()`s nor `print()`s appear in the email. The bug report view is missing the "Include Console Log" cell.

**Comment by mliberatore** [comment]
Please see the [Features](https://github.com/Lickability/PinpointKit#features) section of the README. Specifically:

> Automatic, opt-in system log collection (iOS 9.x only)

Unfortunately, the default logger is disabled in iOS 10+ by default because of the issues documented [here](https://github.com/Lickability/PinpointKit/issues/205).

**Comment by iosdeveloper** [comment]
@mliberatore Thanks! Just to be clear, the suggested workaround would be to set a custom LogCollector?

**Comment by mliberatore** [comment]
That’s correct! If you have a custom type that conforms to `LogCollector`, you’ll need to do the following:

* Create an instance of `Configuration`, passing in an instance of your custom log collector for the [`logCollector` parameter on `init`](https://github.com/Lickability/PinpointKit/blob/master/PinpointKit/PinpointKit/Sources/Core/Configuration.swift#L57).
* Use [the initializer on `PinpointKit` that allows you to specify a `Configuration`](https://github.com/Lickability/PinpointKit/blob/master/PinpointKit/PinpointKit/Sources/Core/PinpointKit.swift#L29), and pass in the instance you created in the previous step.
