### ISSUE TITLE
No way to notify users via UI in case of mail failure

### ISSUE THREAD

**Issue by sxmichaels** [Lickability/PinpointKit#219]
When sending mail fails, [only a small message is printed via NSLog](https://github.com/Lickability/PinpointKit/blob/c3bbb00f8cf605360abfc93b0147e1eb626dca91/PinpointKit/PinpointKit/Sources/Core/PinpointKit.swift#L89). There seems to be no way to configure PinpointKit to react to this situation in the GUI.

I'd like instead to pop up an alert to notify the user via the UI, and dismiss the PinpointKit view controller, but as best as I can tell the current design doesn't allow me to do so either via delegates (`PinpointKitDelegate` has no "mail failed" function) or overrides (as I cannot set the `SenderDelegate` to a new class and still get access to PinpointKit's private `displayingViewController` within that class, which I would need to dismiss the view on successful sending like the default does). I also need to do this in the case where the view is brought up via shaking, so I can't assume I just have a reference to the presenting VC.

**Comment by mattbischoff** [comment]
@sxmichaels Thanks for the detailed report. Would you be open to proposing a PR that would give you the access / information you needed here for us to review?

**Comment by sxmichaels** [comment]
Sure; I'm a bit busy now but could put one together in the next few weeks. What kind of solution would you find acceptable, roughly? I'm thinking of adding a `didFailToSend ` function to the `PinpointKitDelegate` and displaying an `NSAlert` on failure instead of (or in addition to) the `NSLog` invocation I mentioned above.

**Comment by mliberatore** [comment]
Hi @sxmichaels. If you’re looking for a quick solution, we offer the ability to customize the `Sender`. Take a look at this sample code which gets the job done. You’re proposed solution sounds good to us as well, so feel free to put together a pull request when you have the time.

```swift
import UIKit
import PinpointKit

final class ViewController: UITableViewController {
    
    var pinpointKit: PinpointKit?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Hides the infinite cells footer.
        tableView.tableFooterView = UIView()
        
        let sender = MailSender()
        let feedbackConfiguration = FeedbackConfiguration(recipients: ["feedback@example.com"])
        
        let config = Configuration(sender: sender, feedbackConfiguration: feedbackConfiguration)
        pinpointKit = PinpointKit(configuration: config)
        sender.delegate = self
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        pinpointKit?.show(from: self)
    }
}

extension ViewController: SenderDelegate {
    
    func sender(_ sender: Sender, didSend feedback: Feedback?, success: SuccessType?) {
    
    }
    
    func sender(_ sender: Sender, didFailToSend feedback: Feedback?, error: Error) {
        let alert = UIAlertController(title: "Failed to send mail", message: nil, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .cancel, handler: nil))
        
        presentedViewController?.present(alert, animated: true, completion: nil)
    }
}
```

**Comment by sxmichaels** [comment]
I originally tried to do something like that, but in that case it seems I have no way to dismiss the PinpointKit view controller upon success in `didSend`, because `displayingViewController` is only accessible from within the `PinpointKit` class (see [here](https://github.com/Lickability/PinpointKit/blob/c3bbb00f8cf605360abfc93b0147e1eb626dca91/PinpointKit/PinpointKit/Sources/Core/PinpointKit.swift#L79)) and AFAIK PinpointKit doesn't expose any other function I can use to close it.
