### ISSUE TITLE
Compiler error with Swift 3.2

### ISSUE THREAD

**Issue by derrickshowers** [Lickability/PinpointKit#222]
There are a bunch of errors coming from Configuration.swift when building with the Xcode 9 beta (I suspect related to Swift 3.2). I did some quick checking to see what might have changed, but have thus far been able to come up with anything. 🤔 

The errors are: 
`Immutable value 'self.feedbackCollector' may only be initialized once`
`Immutable value 'self.feedbackCollector' may only be initialized once`

... and so on for all instances where properties on `feedbackCollector` are being modified. I have [a simple fix](https://github.com/derrickshowers/PinpointKit/commit/58e0fab99fd6a8bc91b62d454d036f1769051187) on my Github. Happy to open a PR if you'd like.

**Comment by mliberatore** [comment]
Hi @derrickshowers! Thanks for filing this. I’ve put up a pull request into `develop` (#227) to address this problem in a slightly different way that keeps `Configuration`’s `feedbackCollector` a `let` constant. Thanks for using PinpointKit!

**Comment by derrickshowers** [comment]
Great. Thanks!

**Comment by mliberatore** [comment]
Closed via #227
