### ISSUE TITLE
[iOS 11] Blur Annotation Delayed While Dragging

### ISSUE THREAD

**Issue by mliberatore** [Lickability/PinpointKit#223]
When initially drawing a blur annotation via dragging after selecting it, it doesn’t appear for a few seconds. It will appear after if you hold the drag long enough, or after you’ve ended the drag.

1. Launch `PinpointKitExample`.
1. Tap the photo.
1. Choose the blur annotation.
1. Drag along the photo to draw a blur annotation.
1. Notice that it did’t appear right away as you were dragging like an arrow or box annotation would.

**Comment by mliberatore** [comment]
**Note:** It’s likely related that all other annotations take just a little while longer than they used to to appear. If it’s found that this isn’t the case, please file a separate issue.

**Comment by Twigz** [comment]
Looks like this only happens on simulator.
