### ISSUE TITLE
New Release for Swift 4 / Xcode 9

### ISSUE THREAD

**Issue by leedsalex** [Lickability/PinpointKit#231]
Could you please tag up a new release for Swift 4 & Xcode 9. I am currently using `master` but it would be nice to have a new version.

**Comment by Twigz** [comment]
Hi @leedsalex,

We have two issues we're working on before we cut the next release:
https://github.com/Lickability/PinpointKit/issues/223
https://github.com/Lickability/PinpointKit/issues/224

After we finish up those we'll be cutting a new version of the framework (which will hopefully be this Friday).

**Comment by leedsalex** [comment]
Thank you for tagging the release!
