### ISSUE TITLE
Add Swift Package Manager Support

### ISSUE THREAD

**Issue by mliberatore** [Lickability/PinpointKit#264]
# Feature Proposal
In Xcode 11, we can now use Swift Package Manager for dependencies. Perform the necessary work for others to integrate PinpointKit as a Swift Package.

**Comment by leisurehound** [comment]
Is the ASLLogger.h/.m the only thing that is making SPM support the challenge?  It seems these aspects are no-ops for iOS 10+ anyway.  While I wouldn't want to iOS 9.3 support to be dropped, what is the impact of ASLLogging no-op'ing on iOS 9 compared to iOS 10+ anyway?  Seems like a simpler tradeoff for the minimal positive impact of having the logs on such a small userebase and simplifies the SPM support.
