### ISSUE TITLE
Support 'limited' photo authorization for iOS 14

### ISSUE THREAD

**Issue by leisurehound** [Lickability/PinpointKit#275]
# Feature Proposal
iOS 14 adds a new authorization status beyond .authorized, .denied, .restricted of .limited.  In requiresPhotoAuthorization() a compiler warning is raised that the switch is not exhaustive.  

## Constraints and Assumptions
If a user selects .limited the library should still work.

**Comment by mattbischoff** [comment]
Fixed in #278 (version 1.5.0).
