### ISSUE TITLE
Release New Version Supporting Swift Package Manager

### ISSUE THREAD

**Issue by mliberatore** [Lickability/PinpointKit#283]
# Engineering Task
#280 added Swift Package Manager support. You can currently integrate PinpointKit via SPM by selecting the `master` branch in Package Options, but the `Package.swift` addition came after the latest version (1.5.0), so selecting a version requirement will fail as expected with:

```
https://github.com/Lickability/PinpointKit.git has no Package.swift manifest for version 1.5.0
```

## Constraints and Assumptions
N/A

## Design and Product Information
N/A

**Comment by chbeer** [comment]
What is missing for adding Package.swift to a 1.5.1? I would love to switch to SPM for this!

**Comment by mattbischoff** [comment]
@chbeer Good news there! You can swift to SPM today by setting it up like this and pointing directly at the `master` branch or a commit that you'd like to pin to.

<img width="788" alt="Screen Shot 2021-09-16 at 3 12 26 PM" src="https://user-images.githubusercontent.com/14093/133671596-53398877-09e8-484c-912a-009e936f9943.png">
